# Generated by Django 2.2.5 on 2019-09-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reliantparty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliantparty',
            name='address_post_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliantparty',
            name='address_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliantparty',
            name='address_street_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliantparty',
            name='address_street_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reliantparty',
            name='contact_phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
